version: '3'

services:
  db:
    image: postgres:14.3
    # restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    container_name: teslo-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
